{% set name = "opentelemetry-instrumentation-sqlalchemy" %}
{% set version = "0.42b0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentelemetry_instrumentation_sqlalchemy-{{ version }}.tar.gz
  sha256: a329a9c24f39267622a5157b23cda5b7fa22ddc762d5c3e41248ff508d7ff52a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
    - hatchling
  run:
    - python >=3.7
    - opentelemetry-api ~=1.12
    - opentelemetry-instrumentation ==0.42b0
    - opentelemetry-semantic-conventions ==0.42b0
    - packaging >=21.0
    - wrapt >=1.11.2
    # - sqlalchemy 
    # - pytest 
    # - opentelemetry-sdk ~=1.12
    # - opentelemetry-instrumentation-sqlalchemy 
    # - sqlalchemy 
    # - pytest 
    # - opentelemetry-sdk ~=1.12
    # - opentelemetry-instrumentation-sqlalchemy 
    # - sqlalchemy 
    # - pytest 
    # - opentelemetry-sdk ~=1.12
    # - opentelemetry-instrumentation-sqlalchemy 
    # - sqlalchemy 
    # - pytest 
    # - opentelemetry-sdk ~=1.12
    # - opentelemetry-instrumentation-sqlalchemy 
    # - sqlalchemy 
    # - pytest 
    # - opentelemetry-sdk ~=1.12
    # - opentelemetry-instrumentation-sqlalchemy 
    # - sqlalchemy 
    # - pytest 
    # - opentelemetry-sdk ~=1.12
    # - opentelemetry-instrumentation-sqlalchemy 

test:
  imports:
    - opentelemetry
    - opentelemetry.instrumentation
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/open-telemetry/opentelemetry-python-contrib/tree/main/instrumentation/opentelemetry-instrumentation-sqlalchemy
  summary: OpenTelemetry SQLAlchemy instrumentation
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
    - mariusvniekerk
